services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=db;Database=investhub;Username=admin;Password=investhub1234
        depends_on:
            - db
        networks:
            - investhub

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: investhub1234
            POSTGRES_DB: investhub
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - investhub

volumes:
    postgres_data:

networks:
    investhub: