// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using investhub_backend.DbContextInvesthub;

#nullable disable

namespace investhub_backend.Migrations
{
    [DbContext(typeof(InvesthubDBContext))]
    [Migration("20240923182402_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("investhub_backend.Data.Models.Accion", b =>
                {
                    b.Property<int>("AccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccionId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<float>("PrecioCompra")
                        .HasColumnType("real");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("integer");

                    b.HasKey("AccionId");

                    b.HasIndex("PortafolioId");

                    b.ToTable("Accione");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Ahorro", b =>
                {
                    b.Property<int>("AhorroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AhorroId"));

                    b.Property<float>("Cantidad")
                        .HasColumnType("real");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<int>("tipoMoneda")
                        .HasColumnType("integer");

                    b.HasKey("AhorroId");

                    b.HasIndex("PortafolioId");

                    b.ToTable("Ahorro");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<int>("EmailId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmailId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmailId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Email");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Portafolio", b =>
                {
                    b.Property<int>("PortafolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PortafolioId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.HasKey("PortafolioId");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Accion", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Portafolio", "Portafolio")
                        .WithMany("Acciones")
                        .HasForeignKey("PortafolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Ahorro", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Portafolio", "Portafolio")
                        .WithMany("Ahorros")
                        .HasForeignKey("PortafolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Email", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Cliente", "Cliente")
                        .WithOne("Email")
                        .HasForeignKey("investhub_backend.Data.Models.Email", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Portafolio", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Cliente", "Cliente")
                        .WithOne("Portafolio")
                        .HasForeignKey("investhub_backend.Data.Models.Portafolio", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Cliente", b =>
                {
                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Portafolio")
                        .IsRequired();
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Portafolio", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Ahorros");
                });
#pragma warning restore 612, 618
        }
    }
}
