// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using investhub_backend.DbContextInvesthub;

#nullable disable

namespace investhub_backend.Migrations
{
    [DbContext(typeof(InvesthubDBContext))]
    partial class InvesthubDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("investhub_backend.Data.Models.Accion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<float>("PrecioActual")
                        .HasColumnType("real");

                    b.Property<float>("PrecioCompra")
                        .HasColumnType("real");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortafolioId");

                    b.ToTable("Accion");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Ahorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Cantidad")
                        .HasColumnType("real");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<int>("tipoMoneda")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortafolioId");

                    b.ToTable("Ahorro");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmailId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortafolioId")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("PortafolioId")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Portafolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Accion", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Portafolio", "Portafolio")
                        .WithMany("Acciones")
                        .HasForeignKey("PortafolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Ahorro", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Portafolio", "Portafolio")
                        .WithMany("Ahorros")
                        .HasForeignKey("PortafolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Cliente", b =>
                {
                    b.HasOne("investhub_backend.Data.Models.Email", "Email")
                        .WithOne("cliente")
                        .HasForeignKey("investhub_backend.Data.Models.Cliente", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("investhub_backend.Data.Models.Portafolio", "Portafolio")
                        .WithOne("Cliente")
                        .HasForeignKey("investhub_backend.Data.Models.Cliente", "PortafolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Portafolio");
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Email", b =>
                {
                    b.Navigation("cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("investhub_backend.Data.Models.Portafolio", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Ahorros");

                    b.Navigation("Cliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
